/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jazmin
 */
public class Vista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Vista.class.getName());

    /**
     * Creates new form Vista
     */
    private clienteControlador controlador;
    private autoControlador controladorAuto;
    private serviciosControlador controladorServicios;
    
    
    public Vista() {
        initComponents();
        
        controlador = new clienteControlador(this);
        controladorAuto = new autoControlador(this);
        controladorServicios = new serviciosControlador(this);
        inicializarTablaServicios(); 
        
        ((javax.swing.table.DefaultTableModel) jTableClientesTicket.getModel()).setRowCount(0);
        jTableClientesTicket.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        
        jTabbedPane1.setEnabledAt(1, false); // Vehículo
        jTabbedPane1.setEnabledAt(2, false); // Servicios
        jTabbedPane1.setEnabledAt(3, false); // Ticket
        
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelCliente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id_cliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_Nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Apellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Telefono = new javax.swing.JTextField();
        JButton_RegistroCliente = new javax.swing.JButton();
        jPanelVehiculo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelClienteActivo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAutos = new javax.swing.JTable();
        jButtonEliminarAuto = new javax.swing.JButton();
        jButtonAgregarAuto1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanelServicios = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAutosServicios = new javax.swing.JTable();
        jCheckBoxExterior = new javax.swing.JCheckBox();
        jCheckBoxInterior = new javax.swing.JCheckBox();
        jCheckBoxEncerado = new javax.swing.JCheckBox();
        jCheckBoxPulido = new javax.swing.JCheckBox();
        jButtonAsignarServicio = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButtonPasarTicket = new javax.swing.JButton();
        jPanelTicket = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableClientesTicket = new javax.swing.JTable();
        jButtonMostrarTicket = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de los datos del cliente");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Id. Cliente");

        id_cliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        id_cliente.addActionListener(this::id_clienteActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nombre");

        jTextField_Nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_Nombre.addActionListener(this::jTextField_NombreActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Apellido");

        jTextField_Apellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_Apellido.addActionListener(this::jTextField_ApellidoActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Telefono");

        jTextField_Telefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_Telefono.addActionListener(this::jTextField_TelefonoActionPerformed);

        JButton_RegistroCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JButton_RegistroCliente.setText("Registrar");
        JButton_RegistroCliente.addActionListener(this::JButton_RegistroClienteActionPerformed);

        javax.swing.GroupLayout jPanelClienteLayout = new javax.swing.GroupLayout(jPanelCliente);
        jPanelCliente.setLayout(jPanelClienteLayout);
        jPanelClienteLayout.setHorizontalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelClienteLayout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(jTextField_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelClienteLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jTextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClienteLayout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(JButton_RegistroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(355, Short.MAX_VALUE))
        );
        jPanelClienteLayout.setVerticalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(JButton_RegistroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cliente", jPanelCliente);

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("REGISTRO AUTO");

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel7.setText("Cliente:");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("GUARDAR");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 0), new java.awt.Color(51, 153, 0), new java.awt.Color(51, 51, 51), new java.awt.Color(0, 51, 51)));
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabelClienteActivo.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabelClienteActivo.setText("-");

        jTableAutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Auto", "Cliente", "Modelo", "Color", "Tipo", "Observaciones", "Cita", "Hora"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableAutos);

        jButtonEliminarAuto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonEliminarAuto.setText("Eliminar auto");
        jButtonEliminarAuto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 0), new java.awt.Color(51, 153, 0), new java.awt.Color(51, 51, 51), new java.awt.Color(0, 51, 51)));
        jButtonEliminarAuto.addActionListener(this::jButtonEliminarAutoActionPerformed);

        jButtonAgregarAuto1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonAgregarAuto1.setText("Agregar auto");
        jButtonAgregarAuto1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 0), new java.awt.Color(51, 153, 0), new java.awt.Color(51, 51, 51), new java.awt.Color(0, 51, 51)));
        jButtonAgregarAuto1.addActionListener(this::jButtonAgregarAuto1ActionPerformed);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("IR A SERVICIOS");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 0), new java.awt.Color(51, 153, 0), new java.awt.Color(51, 51, 51), new java.awt.Color(0, 51, 51)));
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout jPanelVehiculoLayout = new javax.swing.GroupLayout(jPanelVehiculo);
        jPanelVehiculo.setLayout(jPanelVehiculoLayout);
        jPanelVehiculoLayout.setHorizontalGroup(
            jPanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVehiculoLayout.createSequentialGroup()
                .addGroup(jPanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVehiculoLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVehiculoLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jButtonAgregarAuto1)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminarAuto)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanelVehiculoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelVehiculoLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addGroup(jPanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelClienteActivo, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanelVehiculoLayout.setVerticalGroup(
            jPanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVehiculoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel6)
                .addGap(22, 22, 22)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelClienteActivo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addGap(9, 9, 9)
                .addGroup(jPanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonEliminarAuto)
                    .addComponent(jButtonAgregarAuto1)
                    .addComponent(jButton2))
                .addGap(15, 15, 15))
        );

        jTabbedPane1.addTab("Vehiculo", jPanelVehiculo);

        jTableAutosServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cliente", "ID auto", "Modelo", "Color", "Tipo", "Servicios"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableAutosServicios);

        jCheckBoxExterior.setText("Lavado exterior");
        jCheckBoxExterior.addActionListener(this::jCheckBoxExteriorActionPerformed);

        jCheckBoxInterior.setText("Lavado interior");

        jCheckBoxEncerado.setText("Encerado");

        jCheckBoxPulido.setText("Pulido de faros");

        jButtonAsignarServicio.setText("Asignar servicios");
        jButtonAsignarServicio.addActionListener(this::jButtonAsignarServicioActionPerformed);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Registro de servicios a vehiculos");
        jLabel8.setToolTipText("");

        jButtonPasarTicket.setText("Ir a Ticket");
        jButtonPasarTicket.addActionListener(this::jButtonPasarTicketActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBoxInterior, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxExterior, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxEncerado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxPulido, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAsignarServicio)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPasarTicket)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxExterior)
                            .addComponent(jCheckBoxEncerado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxInterior)
                            .addComponent(jCheckBoxPulido)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAsignarServicio)
                            .addComponent(jButtonPasarTicket))))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelServiciosLayout = new javax.swing.GroupLayout(jPanelServicios);
        jPanelServicios.setLayout(jPanelServiciosLayout);
        jPanelServiciosLayout.setHorizontalGroup(
            jPanelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelServiciosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelServiciosLayout.setVerticalGroup(
            jPanelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelServiciosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Servicios", jPanelServicios);

        jTableClientesTicket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Apellido", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableClientesTicket);

        jButtonMostrarTicket.setText("Mostrar ticket");
        jButtonMostrarTicket.addActionListener(this::jButtonMostrarTicketActionPerformed);

        javax.swing.GroupLayout jPanelTicketLayout = new javax.swing.GroupLayout(jPanelTicket);
        jPanelTicket.setLayout(jPanelTicketLayout);
        jPanelTicketLayout.setHorizontalGroup(
            jPanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(jPanelTicketLayout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jButtonMostrarTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
        );
        jPanelTicketLayout.setVerticalGroup(
            jPanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTicketLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMostrarTicket)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ticket", jPanelTicket);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void id_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_clienteActionPerformed

    private void jTextField_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NombreActionPerformed

    private void jTextField_ApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ApellidoActionPerformed

    private void jTextField_TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TelefonoActionPerformed

    private void JButton_RegistroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_RegistroClienteActionPerformed
        // TODO add your handling code here:
        controlador.JButton_RegistroCliente();
    }//GEN-LAST:event_JButton_RegistroClienteActionPerformed

    private void jButtonMostrarTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarTicketActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = jTableClientesTicket.getSelectedRow();
        controlador.mostrarTicket(filaSeleccionada);
    }//GEN-LAST:event_jButtonMostrarTicketActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        controladorAuto.guardarAutos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonEliminarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarAutoActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = jTableAutos.getSelectedRow();
            if (filaSeleccionada == -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Selecciona una fila para eliminar.");
                return;
    }
    ((javax.swing.table.DefaultTableModel) jTableAutos.getModel()).removeRow(filaSeleccionada);
    }//GEN-LAST:event_jButtonEliminarAutoActionPerformed

    private void jButtonAgregarAuto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarAuto1ActionPerformed
        // TODO add your handling code here:
        javax.swing.table.DefaultTableModel modelo = 
        (javax.swing.table.DefaultTableModel) jTableAutos.getModel();
    
            String horaActual = java.time.LocalTime.now()
                            .truncatedTo(java.time.temporal.ChronoUnit.MINUTES)
                            .toString();
    
            // Columnas: ID Auto | Cliente | Modelo | Color | Tipo | Observaciones | Cita | Hora
            modelo.addRow(new Object[]{
                String.format("%04d", controladorAuto.getSiguienteIdAuto()),
                jLabelClienteActivo.getText(),
                "", "", "", "", "", horaActual
            });
    }//GEN-LAST:event_jButtonAgregarAuto1ActionPerformed

    private void jCheckBoxExteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxExteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxExteriorActionPerformed

    private void jButtonAsignarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsignarServicioActionPerformed
        // TODO add your handling code here:
        controladorServicios.asignarServicio();
    }//GEN-LAST:event_jButtonAsignarServicioActionPerformed

    private void jButtonPasarTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPasarTicketActionPerformed
        // TODO add your handling code here:
        habilitarTab(3);
    }//GEN-LAST:event_jButtonPasarTicketActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        controladorAuto.onComboClienteChanged();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        habilitarTab(2);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Vista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_RegistroCliente;
    private javax.swing.JTextField id_cliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAgregarAuto1;
    private javax.swing.JButton jButtonAsignarServicio;
    private javax.swing.JButton jButtonEliminarAuto;
    private javax.swing.JButton jButtonMostrarTicket;
    private javax.swing.JButton jButtonPasarTicket;
    private javax.swing.JCheckBox jCheckBoxEncerado;
    private javax.swing.JCheckBox jCheckBoxExterior;
    private javax.swing.JCheckBox jCheckBoxInterior;
    private javax.swing.JCheckBox jCheckBoxPulido;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelClienteActivo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCliente;
    private javax.swing.JPanel jPanelServicios;
    private javax.swing.JPanel jPanelTicket;
    private javax.swing.JPanel jPanelVehiculo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableAutos;
    private javax.swing.JTable jTableAutosServicios;
    private javax.swing.JTable jTableClientesTicket;
    private javax.swing.JTextField jTextField_Apellido;
    private javax.swing.JTextField jTextField_Nombre;
    private javax.swing.JTextField jTextField_Telefono;
    // End of variables declaration//GEN-END:variables

public javax.swing.JTextField getIdCliente() {
    return id_cliente;
}

public javax.swing.JTextField getNombre() {
    return jTextField_Nombre;
}

public javax.swing.JTextField getApellido() {
    return jTextField_Apellido;
}

public javax.swing.JTextField getTelefono() {
    return jTextField_Telefono;
}

public serviciosControlador getControladorServicios() {
    return controladorServicios;
}

public javax.swing.table.DefaultTableModel getModeloTabla() {
    return (javax.swing.table.DefaultTableModel) jTableClientesTicket.getModel();
}

public void habilitarTab(int indice) {
    jTabbedPane1.setEnabledAt(indice, true);
    jTabbedPane1.setSelectedIndex(indice);
}

public void inicializarTablaAutos() {
    javax.swing.table.DefaultTableModel modeloAutos = new javax.swing.table.DefaultTableModel(
        new Object[][]{},
        new String[]{"ID Auto", "Cliente", "Modelo", "Color", "Tipo", "Observaciones", "Cita", "Hora"}
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            // ID Auto y Cliente no editables
            return column != 0 && column != 1;
        }
    };
    jTableAutos.setModel(modeloAutos);
    javax.swing.JComboBox<String> comboTipo = new javax.swing.JComboBox<>(
        new String[]{"Sedán", "SUV", "Pickup", "Moto"}
    );
    jTableAutos.getColumnModel().getColumn(4)
        .setCellEditor(new javax.swing.DefaultCellEditor(comboTipo));
}

public void inicializarTablaServicios() {
    jTableAutosServicios.getSelectionModel().addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            controladorServicios.cargarServiciosDelAuto();
        }
    });
}

public javax.swing.JTable getTablaAutos() {
    return jTableAutos;
    
}

public String getClienteActivo() {
    return jLabelClienteActivo.getText();
}

public autoControlador getControladorAuto() {
    return controladorAuto;
}

public void setClienteActivo(String nombre) {
    jLabelClienteActivo.setText(nombre);
}

public javax.swing.JTable getTablaAutosServicios() {
    return jTableAutosServicios;
}

public void cargarAutosEnServicios(java.util.ArrayList<Auto> autos, String nombreCliente) {
    javax.swing.table.DefaultTableModel modelo = 
        (javax.swing.table.DefaultTableModel) jTableAutosServicios.getModel();
    modelo.setRowCount(0);
    for (Auto a : autos) {
        modelo.addRow(new Object[]{
            nombreCliente,
            a.getId_auto(),
            a.getModelo(),
            a.getColor(),
            a.getTipo()
        });
    }
}

public void agregarAutosEnServicios(java.util.ArrayList<Auto> autos, String nombreCliente) {
    javax.swing.table.DefaultTableModel modelo =
        (javax.swing.table.DefaultTableModel) jTableAutosServicios.getModel();
    for (Auto a : autos) {
        modelo.addRow(new Object[]{
            nombreCliente,
            a.getId_auto(),
            a.getModelo(),
            a.getColor(),
            a.getTipo()
        });
    }
}

public void agregarClienteAlCombo(int idCliente, String nombreCompleto) {
    String item = String.format("%04d – %s", idCliente, nombreCompleto);
    jComboBox1.addItem(item);
    jComboBox1.setSelectedItem(item);
    jLabelClienteActivo.setText(nombreCompleto);
}

public javax.swing.JComboBox<String> getComboClientes() {
    return jComboBox1;
}

public javax.swing.JCheckBox getCheckExterior()  { return jCheckBoxExterior; }
public javax.swing.JCheckBox getCheckInterior()  { return jCheckBoxInterior; }
public javax.swing.JCheckBox getCheckEncerado()  { return jCheckBoxEncerado; }
public javax.swing.JCheckBox getCheckPulido()    { return jCheckBoxPulido;   }



}